### DISCUSSION TITLE
DFN schema/format

### DISCUSSION THREAD

**Discussion by wpbonelli** [pyphoenix/pyphoenix-project#47] [Ideas]
We have arrived at TOML as the tentative format for definition files. TOML is visually similar to existing definition files, while allowing a structured representation of the block/variable tree.

As @deltamarnix has suggested DFN files should be versioned. We can consider legacy DFNs version 1. The TOML format can be 2(.0.0), then whenever we make a change to the format (e.g. adding/removing an attribute) we bump the version number, so consumers can explicitly decide whether they support a given DFN file without having to try and parse it all.

After chatting on an initial draft in https://github.com/modflowpy/flopy/pull/2333#issuecomment-2463070065 it sounds like we want blocks at the top level, rather than variables, and to omit explicit child attributes in favor of attaching children directly to the parent. So the example would become

```toml

name = "prt-oc"
multi = false
stress = false
advanced = false

[options.budget_filerecord]
type = "record"

[options.budget_filerecord.budget]
type = "keyword"
reader = "urword"
optional = false
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[options.budget_filerecord.fileout]
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[options.budget_filerecord.budgetfile]
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the output file to write budget information."

...
```

Period block specifications could look like

```toml
...

[period.iper]
type = "integer"
block_index = true
reader = "urword"
optional = false
longname = "stress period number"
description = "integer value specifying the stress period number for which the data specified in the PERIOD block apply. IPER must be less than or equal to NPER in the TDIS Package and greater than zero. The IPER value assigned to a stress period block must be greater than the IPER value assigned for the previous PERIOD block. The information specified in the PERIOD block applies only to that stress period."

[period.perioddata]
type = "list"
reader = "urword"
optional = false

[period.perioddata.releasesetting]
type = "record"
reader = "urword"
optional = false

[period.perioddata.releasesetting.all]
type = "keyword"
reader = "urword"
description = "keyword to indicate release of particles at the start of all time steps in the period."

[period.perioddata.releasesetting.first]
type = "keyword"
reader = "urword"
description = "keyword to indicate release of particles at the start of the first time step in the period. This keyword may be used in conjunction with other keywords to release particles at the start of multiple time steps."

[period.perioddata.releasesetting.frequency]
type = "integer"
reader = "urword"
description = "release particles at the specified time step frequency. This keyword may be used in conjunction with other keywords to release particles at the start of multiple time steps."

[period.perioddata.releasesetting.steps]
type = "integer"
shape = "(<nstp)"
reader = "urword"
description = "release particles at the start of each step specified in STEPS. This keyword may be used in conjunction with other keywords to release particles at the start of multiple time steps."
...

Setting `block_index` for an integer top-level block variable can indicate transient data, otherwise the block is handled normally
```

This has not been implemented yet in the referenced PR or here. It could maybe be prototyped here, moved to flopy3 when ready, and then moved to devtools once we're confident in it.

**Comment by wpbonelli** [comment]
The format above has been implemented in devtools:

- https://github.com/MODFLOW-USGS/modflow-devtools/pull/167
- https://github.com/MODFLOW-USGS/modflow-devtools/pull/173

I'm presently working it into https://github.com/modflowpy/flopy/pull/2333.

I'm having second thoughts about the "implicit" nesting. Looking elsewhere for precedent, the convention [in pyproject.toml files](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/) is to name collections explicitly. E.g. `[tool.pixi.feature.lint.tasks]`. This is more verbose, but clearer (imo) and easier to work with programmatically (no need to filter entries to find children).

E.g. `[options.cvoptions.dewatered]` is concise but `[block.options.cvoptions.fields.dewatered]` makes it clearer from the table path that this variable is part of a record, that it's a member of the options **block** rather than some other notion of options relevant to definition files more generally, etc.

It seems better to have a fixed top-level schema with a `blocks` table whose entries vary by component rather than some minimal set of top-level attributes and no restrictions on top-level block names.

Explicitness also seems preferable in toml in general because nested structures are not obvious to the eye, as they would be in yaml or json. Issue 781 on the toml repo is an interesting discussion of toml's approach to nested data.

**Reply by wpbonelli** [reply]
Removed the top-level `blocks` table in https://github.com/MODFLOW-USGS/modflow-devtools/pull/177 after marinating more. Blocks now sit at the top level. Variables still have explicit tables for children:

- `item` for lists
- `choices` for unions
- `fields` for records

For example

```toml
[period.stress_period_data]
name = "stress_period_data"
type = "list"
shape = "(maxbound)"
reader = "urword"
mf6internal = "spd"

[period.stress_period_data.item]
name = "stress_period_data"
type = "record"
reader = "urword"
mf6internal = "spd"

[period.stress_period_data.item.fields.cellid]
name = "cellid"
type = "integer"
shape = "(ncelldim)"
reader = "urword"
longname = "cell identifier"
description = "is the cell identifier, and depends on the type of grid that is used for the simulation.  For a structured grid that uses the DIS input file, CELLID is the layer, row, and column.   For a grid that uses the DISV input file, CELLID is the layer and CELL2D number.  If the model uses the unstructured discretization (DISU) input file, CELLID is the node number for the cell."
```

IMO less verbose, but still clear, also emphasizes the distinction between blocks and variables &mdash; both really can be considered product types but mf6 considers them distinct: blocks sit at the top level of a component definition, contain variables directly, and have no other attributes*. Variables must be inside a block or another variable, and can have arbitrary attributes (for now &mdash; eventually lock it down).

*`iper` is a `block_variable`, but imo this is an mf6 io format detail and flopy4 can probably consider a transient block a variable with an extra time dimension? https://github.com/MODFLOW-USGS/modflow-devtools/pull/178 moves in this direction.

Lists remain the most awkward type to express. In the current DFNs a variable with `type recarray` can be a list of records, or of unions of records

- list of records `type recarray cellid head aux boundname`, where the record fields are defined inline
- list of unions `type recarray releasesetting`, where `releasesetting` is a `keystring` variable

There is no such thing as a list of scalars, that's an array from mf6's perspective.

In the TOML format these are now

- `[...<var>.item.fields...]`
- `[...<var>.item.choices...]`

I'm not convinced this is the best way, though.
